# Generated by Django 5.0 on 2024-01-12 12:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projApp', '0002_vacancy_user_age_user_email_user_f_name_user_l_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'skill',
                'verbose_name_plural': 'skills',
            },
        ),
        migrations.CreateModel(
            name='VacancySkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'vacancy_skills',
                'verbose_name_plural': 'vacancy_skills',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='userskills',
            options={'verbose_name': 'user_skills', 'verbose_name_plural': 'user_skills'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'vacancy', 'verbose_name_plural': 'vacancies'},
        ),
        migrations.AddField(
            model_name='vacancy',
            name='area_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 12, 17, 37, 35, 717468)),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userskills',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='projApp.user'),
        ),
        migrations.AddField(
            model_name='userskills',
            name='skills',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='projApp.skills'),
        ),
        migrations.AddConstraint(
            model_name='userskills',
            constraint=models.UniqueConstraint(fields=('user', 'skills'), name='cnstr_us'),
        ),
        migrations.AddField(
            model_name='vacancyskills',
            name='skills',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='projApp.skills'),
        ),
        migrations.AddField(
            model_name='vacancyskills',
            name='vacancy',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='projApp.vacancy'),
        ),
        migrations.AddConstraint(
            model_name='vacancyskills',
            constraint=models.UniqueConstraint(fields=('vacancy', 'skills'), name='cnstr_vs'),
        ),
    ]
